server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    user-service-group-id: user-service-group
    user-service-admin-group-id: user-service-admin-group
HOSTNAME: localhost